# $Id$

DOCUMENTS=	risksem.pdf
FILES=		risksem.tex aims.tex literature.tex risksem.bib

risksem.pdf: ${FILES}
risksem.pdf: llncs biblatex-lncs


INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
