.PHONY: all
all: gapproject.pdf

gapproject.pdf: ${FILES}
gapproject.pdf: llncs biblatex-lncs

FILES=		gapproject.tex aims.tex gapproject.bib


### INCLUDES ###

INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
