# $Id$

DOCUMENTS=	ismsmemo.pdf
FILES=		ismsmemo.tex aims.tex literature.tex ismsmemo.bib

ismsmemo.pdf: ${FILES}
ismsmemo.pdf: llncs biblatex-lncs


INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
